LEADER_ENABLE = yes
TAP_DANCE_ENABLE = yes
EXTRAKEY_ENABLE = yes

AUDIO_SUPPORTED = no
BACKLIGHT_SUPPORTED = no
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE  = no
CONSOLE_ENABLE   = no
COMMAND_ENABLE   = no
UNICODE_ENABLE   = no
SWAP_HANDS_ENABLE = no
RGB_MATRIX_ENABLE = no

SRC += source.c
